#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mysqltcl
Version  : 3.052
Release  : 1
URL      : https://github.com/xdobry/mysqltcl/archive/3.052.tar.gz
Source0  : https://github.com/xdobry/mysqltcl/archive/3.052.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : libtiff
Requires: mysqltcl-lib = %{version}-%{release}
Requires: mysqltcl-license = %{version}-%{release}
Requires: mysqltcl-man = %{version}-%{release}
BuildRequires : mariadb-dev
BuildRequires : tcl
BuildRequires : tcl-dev

%description
Tcl/Tk 8.0 interface to MySQL
=============================
This is a rewrite of a patched version of Hakan Soderlund's
msqltcl-1.50. I removed all support for older versions of Tcl. If you
are going to use older versions of Tcl, the patch (for msqltcl) found
at http://www.tcx.se will do the job for you.

%package lib
Summary: lib components for the mysqltcl package.
Group: Libraries
Requires: mysqltcl-license = %{version}-%{release}

%description lib
lib components for the mysqltcl package.


%package license
Summary: license components for the mysqltcl package.
Group: Default

%description license
license components for the mysqltcl package.


%package man
Summary: man components for the mysqltcl package.
Group: Default

%description man
man components for the mysqltcl package.


%prep
%setup -q -n mysqltcl-3.052

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556156244
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static --with-mysql-lib=/usr/lib64 \
--with-tcl=/usr/lib64
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
export SOURCE_DATE_EPOCH=1556156244
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mysqltcl
cp COPYING %{buildroot}/usr/share/package-licenses/mysqltcl/COPYING
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/mysqltcl-3.052/pkgIndex.tcl

%files lib
%defattr(-,root,root,-)
/usr/lib64/mysqltcl-3.052/libmysqltcl3.052.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mysqltcl/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/mann/mysqltcl.n
